Name = ("Brian")
Title = ("The Dinosaur Man")
look = ("Dinosaur rings, labcoat and long hair")
Health = ("250")
Ability = ("Mind fucking his opponent causing the target to lose speed, deal less damage and take more damage from all sources")
power = ("Can summon Dinosaurs")
traits = ("does 50% more damage to dinosaur haters")
Wanted = True
weapons = ("Melee: Drumsticks, Ranged: Modified Dinosaur Water Gun")
Special_weapon = ("Grabs a guitar, melee changes to a high damage guitar swing, ranged changes to a barrage of musical notes")
Special_cost = ("200 Mana")
Playstyle = ("Damage dealer")
Duration = ("12 seconds")

print("Champion spotlight")
print("----------------")
print("Champion name:", Name)
print("Title:", Title)
print("Signature Look:", look)
print("Health:", Health)
print("Abilty:", Ability)
print("Special Trait:", traits)
print("Wanted for screwing around with modern day reptile genetics to make dinosaur like killing machines:", Wanted)
print("Unique Weapons:", weapons)
print("Cost of special:", Special_cost)
print("Special Ability:", power)
print("Special Weapon:", Special_weapon)
print("Special Duration:", Duration)
print("Champion Playstyle:", Playstyle)
print("----------------")